// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.7.2
// - protoc             v3.21.7
// source: translate/translate.proto

package translate

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationTranslateText = "/translate.Translate/Text"

type TranslateHTTPServer interface {
	Text(context.Context, *TranslateTextRequest) (*TranslateTextReply, error)
}

func RegisterTranslateHTTPServer(s *http.Server, srv TranslateHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/text", _Translate_Text0_HTTP_Handler(srv))
}

func _Translate_Text0_HTTP_Handler(srv TranslateHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in TranslateTextRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTranslateText)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Text(ctx, req.(*TranslateTextRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*TranslateTextReply)
		return ctx.Result(200, reply)
	}
}

type TranslateHTTPClient interface {
	Text(ctx context.Context, req *TranslateTextRequest, opts ...http.CallOption) (rsp *TranslateTextReply, err error)
}

type TranslateHTTPClientImpl struct {
	cc *http.Client
}

func NewTranslateHTTPClient(client *http.Client) TranslateHTTPClient {
	return &TranslateHTTPClientImpl{client}
}

func (c *TranslateHTTPClientImpl) Text(ctx context.Context, in *TranslateTextRequest, opts ...http.CallOption) (*TranslateTextReply, error) {
	var out TranslateTextReply
	pattern := "/v1/text"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationTranslateText))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
